language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
script: python tests/runtests.py
