language: python
python:
  - "3.8"
env:
  - DJANGO_VERSION=3.2
  - DJANGO_VERSION=4.0
  - DJANGO_VERSION=4.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q django-widget-tweaks==1.4.8
script: python runtests.py
